# Running this docker image runs the integration tests.
FROM golang@sha256:0d1d3a794be25f809dd2cb3160d8c73276c4056a9f8242a138e908ddeee7b6b6

RUN apt-get update -y && apt-get install sudo stunnel4 redis memcached -y && rm -rf /var/lib/apt/lists/*

WORKDIR /workdir

ENV GOPROXY=https://proxy.golang.org
COPY go.mod go.sum /workdir/
RUN go mod download

COPY Makefile /workdir
RUN make bootstrap

COPY src /workdir/src
COPY test /workdir/test
CMD make tests_with_redis
